const mockData = [
    { name: "全车外观清洗，确保无污渍、油渍，驾驶室密封良好。", code: "1.1", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "全车锁具锁止正常，车门开合顺畅，玻璃无划痕。", code: "1.2", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "车辆结构件无弯曲、变形、断裂。", code: "1.3", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "电线与油管排列整齐，固定牢靠，无破损。", code: "1.4", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "配件、叉齿、铲齿完好，无损坏、开裂。", code: "1.5", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "发动机启动后，仪表指示稳定，处于正常范围。", code: "2.1", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "灯光检查仪表灯正常", code: "2.2", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "左前转向灯", code: "2.2.1", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "右前转向灯", code: "2.2.2", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "左后转向灯", code: "2.2.3", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "右后转向灯", code: "2.2.4", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "刹车灯", code: "2.2.5", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "倒车警示灯、刹车灯等。", code: "2.2.5", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "空调功能正常。", code: "2.3.1", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "风扇功能正常。", code: "2.3.2", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "雨刷功能正常。", code: "2.3.3", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "收音机功能正常。", code: "2.3.4", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "安全带等功能正常。", code: "2.3.5", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "仪表显示检查，预热功能、充电电压正常。", code: "2.4", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "动臂、摇臂、拉杆连接良好，销轴安装正常。", code: "3.1", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "液压泵无异响，液压管路无泄漏。", code: "3.2", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "多路阀、优先阀等液压元件固定牢固，无泄漏。", code: "3.3", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "液压操作杆顺畅，无卡滞。", code: "3.4", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "油缸极限伸缩正常，活塞表面无损伤，不漏油。", code: "3.5", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "液压散热器清洁，油箱油位正常。", code: "3.6", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "发动机机油量符合要求，油位正常。", code: "4.1", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "发动机启动平稳，无机油泄漏，皮带张紧正常。", code: "4.2", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "变矩器、变速箱无渗油，变速箱油清澈。", code: "4.3", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "车辆驾驶平稳，挡位切换顺畅，无异常响声。", code: "4.4", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "转向灵敏，方向盘操作顺畅。", code: "4.5", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "刹车油量正常，透明清澈，无泄漏，制动稳定。", code: "4.6", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "万向节间隙适中，传动轴螺栓紧固。", code: "4.7", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "刹车卡钳无异物，刹车片厚度正常，刹车盘无磨损。", code: "4.8", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "前后驱动桥螺丝紧固，标记确认。", code: "4.9", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "手刹拉线松紧适中，手刹片无过度磨损，制动力有效。", code: "4.10", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "轮胎螺栓安装方向正确，并用扭力枪紧固。", code: "4.11", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "装载机收音机搭铁螺丝更换", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "暖水阀开关", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "轮胎螺栓确认(圆弧面向内平面朝外)", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "黄油嘴加注黄油", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "左前轮胎压", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "右前轮胎压", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "左后轮胎压", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "右后轮胎压", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "液压油液位检查", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "柴油油液位检查", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "Picking list 属具打包", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] },
    { name: "电瓶充电", photo: [`http://localhost:5000/images/${Math.floor(Math.random() * 6 + 1)}.jpg`] }
  ];
  
  export default mockData;